local wezterm = require("wezterm")
local M = {}
local flavours = {
  latte = {
    rosewater = "#d94747",
    flamingo = "#d94747",
    red = "#d94747",
    maroon = "#8f2f2f",
    pink = "#a04080",
    mauve = "#a04080",
    peach = "#e86a00",
    yellow = "#d08300",
    green = "#286618",
    teal = "#007a52",
    sky = "#007a52",
    sapphire = "#007a52",
    blue = "#003366",
    lavender = "#2d4d80",
    text = "#754d30",
    subtext1 = "#835939",
    subtext0 = "#90653e",
    overlay2 = "#9c6c45",
    overlay1 = "#9c8e68",
    overlay0 = "#b6a77c",
    surface2 = "#cfc090",
    surface1 = "#e1d3a0",
    surface0 = "#f3e5c0",
    base = "#f9f5d7",
    mantle = "#f0ebc9",
    crust = "#e8e3c3",
  },
  mocha = {
    rosewater = "#f5a8a3",
    flamingo = "#f5a8a3",
    red = "#f5a8a3",
    maroon = "#f5a8a3",
    pink = "#e5b7cb",
    mauve = "#e5b7cb",
    peach = "#f0b688",
    yellow = "#e6c68f",
    green = "#c4d199",
    teal = "#aed2b7",
    sky = "#aed2b7",
    sapphire = "#aed2b7",
    blue = "#a7cdc5",
    lavender = "#a7cdc5",
    text = "#f7efe2",
    subtext1 = "#e6dbc3",
    subtext0 = "#d7cdb4",
    overlay2 = "#c8bfae",
    overlay1 = "#b5aea3",
    overlay0 = "#8c8c8c",
    surface2 = "#818181",
    surface1 = "#757575",
    surface0 = "#5e5e5e",
    base = "#1d2021",
    mantle = "#4d5052",
    crust = "#494c4d",
  },
  mocha_brigth = {
    rosewater = "#f5a8a3",
    flamingo = "#f5a8a3",
    red = "#f5a8a3",
    maroon = "#f5a8a3",
    pink = "#e5b7cb",
    mauve = "#e5b7cb",
    peach = "#f0b688",
    yellow = "#e6c68f",
    green = "#c4d199",
    teal = "#aed2b7",
    sky = "#aed2b7",
    sapphire = "#aed2b7",
    blue = "#a7cdc5",
    lavender = "#a7cdc5",
    text = "#f7efe2",
    subtext1 = "#e6dbc3",
    subtext0 = "#d7cdb4",
    overlay2 = "#c8bfae",
    overlay1 = "#b5aea3",
    overlay0 = "#8c8c8c",
    surface2 = "#818181",
    surface1 = "#757575",
    surface0 = "#5e5e5e",
    base = "#515456",
    mantle = "#4d5052",
    crust = "#494c4d",
  },
  primeppuccin = {
    rosewater = "#e0ceca",
    flamingo = "#e3c1c1",
    pink = "#e0b1d4",
    mauve = "#c4a4eb",
    red = "#d2788c",
    maroon = "#eba0ac",
    peach = "#f6b596",
    yellow = "#e6d0a1",
    green = "#8faf77",
    teal = "#88d1c5",
    sky = "#82d2e0",
    sapphire = "#6dbade",
    blue = "#7aa0de",
    lavender = "#b4befe",
    text = "#d5daf0",
    subtext1 = "#bac2de",
    subtext0 = "#a6adc8",
    overlay2 = "#9399b2",
    overlay1 = "#7f849c",
    overlay0 = "#6c7086",
    surface2 = "#585b70",
    surface1 = "#45475a",
    surface0 = "#313244",
    base = "#1b1f20",
    mantle = "#151819",
    crust = "#0e1011",
  },
}

local function set_colors(flavour)
  return {
    foreground = flavour.text,
    background = flavour.base,
    cursor_bg = flavour.rosewater,
    cursor_border = flavour.rosewater,
    cursor_fg = flavour.crust,
    selection_bg = flavour.surface2,
    selection_fg = flavour.text,
    scrollbar_thumb = flavour.surface2,
    split = flavour.overlay0,
    ansi = {
      flavour.subtext1,
      flavour.red,
      flavour.green,
      flavour.yellow,
      flavour.blue,
      flavour.pink,
      flavour.teal,
      flavour.surface2,
    },
    brights = {
      flavour.subtext0,
      flavour.red,
      flavour.green,
      flavour.yellow,
      flavour.blue,
      flavour.pink,
      flavour.teal,
      flavour.surface1,
    },
    indexed = { [16] = flavour.peach, [17] = flavour.rosewater },
    tab_bar = {
      active_tab = {
        bg_color = flavour.sky,
        fg_color = flavour.crust,
      },
      background = flavour.crust,
      inactive_tab = {
        bg_color = flavour.mantle,
        fg_color = flavour.text,
      },
      inactive_tab_edge = flavour.surface0,
      inactive_tab_hover = {
        bg_color = flavour.base,
        fg_color = flavour.text,
      },
      new_tab = {
        fg_color = flavour.surface0,
        bg_color = flavour.text,
      },
      new_tab_hover = {
        fg_color = flavour.surface1,
        bg_color = flavour.text,
      },
    },
  }
end

M.get_color_scheme = function()
  local hr = tonumber(os.date("%H", os.time()))
  local colors = {}
  if hr > 7 and hr < 16 then
    colors = set_colors(flavours.latte)
    wezterm.log_info("Loading flavor: latte")
  else
    colors = set_colors(flavours.primeppuccin)
    wezterm.log_info("Loading flavor: primeppuccin")
  end
  return colors
end

return M
